site_name: Java code Coverage within Kubernetes
site_url: https://guohai163.github.com/jacoku
repo_url: https://github.com/guohai163/jacoku
repo_name: "guohai163/jacoku"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - content.code.copy
  include_sidebar: true

nav:
  - 快速开始:
    - 项目介绍: "index.md"
    - 快速部署: "depl.md"
  - 完整部署说明:
    - 流程介绍: "full-depl/flow-chart.md"
    - 测试对象准备: "full-depl/test-object.md"
    - 进行测试: "full-depl/testing.md"
    - 生成中间文件: "full-depl/jacoku.md"
  - 二次开发说明: "customization/index.md"